#!/usr/bin/env python3
# -*- coding: utf-8 -*-
REGEX_CLEANER = {
    'common': [r"\s?(\[[^\]]+\]|\([^\)]+\)|\.{3,}|\:{2,}|\,{2,}|\s{2,})\s?", " "],
    'common_posted': [
        r"\s?([\w]+\s\d{1,2},\s\d{4}(\s?by)?|posted\s(o|i)n|\d+\s?Comments|Page\s\d+\s?of\s?\d+|[\-\|\~])\s?", ","],
    'common_url': [r"https?://([A-Za-z_0-9.-]+)(\/[^\s]+)?", r"\1"],
    'common_sampah': [r"\s?([\w-]+.((jpe?|pn)g|gif)|\@|\\ue\d{3,})\s?", ' '],
    'common_before': [r"(^[^\w]+|[^\w]{1,}$)", ''],

}
BLACKLIST_DOMAIN = [
    "cymru.",
    ".abuseat.",
    ".abuse.",
    "wpbl.info",
    "uceprotect.net",
    "dnsbl",
    "dronebl.",
    "sorbs.net",
    "abuse.ch",
    "backscatterer.",
    "manitu.net",
    "korea.services.",
    ".spamrats.",
    ".aupads.",
    ".spamhaus.",
    "proxy.bl.",
    ".fbsbx.",
    ".bet.",
    ".microsoft.",
    ".linkedin.",
    ".charlesproxy.",
    ".mozilla.",
    ".wikipedia.",
    ".google.",
    "fossbytes.",
    "fossmint.",
    ".medium.com",
    "lifewire.",
    ".selenium.",
    "techradar.",
    "scrapingbee.",
    "scrapingdog.",
    ".amazon.",
    "liquidweb.",
    ".netgate.",
    ".redhat.",
    "reviews",
    "serverfault.",
    ".facebook.",
    ".youtube.",
    ".gsa-online.",
    "/(blog|kb|wiki|helps|help|docs|doc)/",
    "wiki.",
    ".godaddy.",
    "idcloak."
]
