from enum import Enum

class Engine(Enum):
	KHTML='KHTML'
	BLINK_WEBKIT='Blink/WebKit'
	WEBKIT_U3='WebKit/U3'
	GOANNA='Goanna'
	PRESTO_BLINK='Presto/Blink'
	GECKO_GOANNA='Gecko/Goanna'
	WEBKIT_BLINK='WebKit/Blink'
	BLINK='Blink'
	PRESTO_WEBKIT='Presto/WebKit'
	TRIDENT_WEBKIT='Trident/WebKit'
	WEBKIT='WebKit'
	TRIDENT='Trident'
	TRIDENT_GECKO_BLINK='Trident/Gecko/Blink'
	GECKO='Gecko'
	WEBKIT_BLINK_GECKO='WebKit/Blink/Gecko'
	GECKO_WEBKIT_WEBKITG='Gecko/WebKit/WebKitG'
	PRESTO='Presto'
	EDGEHTML_WEBKIT_BLI='EdgeHTML//Webkit/Bli'
	EDGEHTML_BLINK='EdgeHTML/Blink'
	WEBKIT_TRIDENT='Webkit/Trident'
	WEBKIT_TRIDENT_BLINK='WebKit/Trident/Blink'
	TRIDENT_WEBKIT_BLINK='Trident/WebKit/Blink'